
function visualize_MD_ROIs(subj_FS,subnum,hemi,which_atlas)
    % function to launch tksurfer and visualize the results of MD 
    % localizer (hard versus easy condition) on inflated 
    % cortical mesh.
    % Assumes that you ran GLM analysis in FSL FEAT, and the results are
    % saved in a folder called AnalyzeMDLocalizer.
    % Will also overlay a cortical segmentation generated by Freesurfer 
    % during recon-all (based on anatomical boundaries identified from 
    % cortical segmentation). If you don't want that, set
    % which_atlas='none'
    
    % Input subject name and hemisphere to look at.
    
    % Once you open it, can use view>window>labels to see the names of all
    % the anatomically-defined areas. 
    %%
    
    if nargin<2
        subj_FS='CP';
        subnum=7;
        hemi='rh';

%         which_atlas='Destrieux';
%         which_atlas='DKT';
        which_atlas='none';
        % can read about these different parcellations at:
        % surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation
    end
    substr =  sprintf('S%02d',subnum);
    % this is a hard coded list of the match between subject inits and
    % numbers for this specific experiment.
    subinit_big = {'BX','BR','CI','CA','CH','AV','CP'};
    subnum_big = {'S01','S02','S03','S04','S05','S06','S07'};
    % make sure we are looking at the correct subject.
    if ~strcmp(subinit_big{strcmp(substr,subnum_big)}, subj_FS)
        error('check your subject number and initial match!')
    end
    
    
    % find my root directory - up a few dirs from where i am now
    mypath = pwd;
    filesepinds = find(mypath==filesep);
    nDirsUp = 2;
    exp_path = mypath(1:filesepinds(end-nDirsUp+1));

    % define the activation map i want to load (generated by FEAT)
    % hard>easy is cope 3 here
    loc_subfolder = 'AnalyzeMDLocalizer';
    overlay_folder = fullfile(exp_path,loc_subfolder,substr,'feats',...
        'AllSessionsFE.gfeat','cope3.feat','stats');
    overlay_file = fullfile(overlay_folder,'tstat1.nii.gz');
%     overlay_file = fullfile(exp_path,'VOIs_parcel',substr,'lh_G_precentral.nii.gz');
%     overlay_file = fullfile(exp_path,'VOIs',substr,'rh_IFS_mdloc.nii.gz');
    
    
    if ~exist(overlay_file,'file')
        error('your digit localizer activation map does not exist yet, did you finish running feat for this subject?')
    end
    
    % get threshold (same method used in getMotorROIs.m)
    cd(overlay_folder)  
    % this is all copied from Find_t_thresh.m
    % get FE dof
    [~, my_FE_dof] = unix('fslstats tdof_t1 -M'); % gives the dof I need for fixed effects (which is the test I ran), output is a string    
    % make log p-stats map
    unix(['ttologp -logpout logp1 varcope1 cope1 ', num2str(str2num(my_FE_dof))]);
    % convert from log to p-value map
    unix(['fslmaths logp1 -exp p1']);    
    % do FDR on p-value map and get probability threshold
    [~,prob_thresh] = unix('fdr -i p1 -q 0.05');
    % go from my p-threshold back into my t-stat
    my_t = abs(tinv(str2num(prob_thresh(28:end)),str2num(my_FE_dof)));
%     my_t=0;
    % define the registration file that's needed to let me project this map
    % into surface space for this subject.
    doreti_folder = '/mnt/neurocube/local/serenceslab/Doreti';
%     reg_file = fullfile(doreti_folder,'FUNC',subj_FS,'PreProc','REG','bbout.reg');
    reg_file = fullfile(exp_path,'DataPreproc',substr,'Func2Anat_auto.dat');
    if ~exist(reg_file,'file')
        error('your Func2Anat_auto.dat file (in preproc folder) is missing for this subject.');
    end
    
    % define the annotation file to show on the surface (segmented cortical
    % regions created during freesurfer's recon-all, which are based on
    % anatomical landmarks).
    if contains(which_atlas,'Dest')
        annot_file = fullfile(doreti_folder,'ANAT',subj_FS,'label',sprintf('%s.aparc.a2009s.annot',hemi));
    elseif strcmp(which_atlas,'DKT')
        annot_file = fullfile(doreti_folder,'ANAT',subj_FS,'label',sprintf('%s.aparc.annot',hemi));
    else
        annot_file = '';
    end
    
    if ~isempty(annot_file) 
        if ~exist(annot_file,'file')
            error('your aparc.a2009s.annot file (in doreti folder) is missing for this subject.');
        end
         % launch tksurfer with the correct arguments
        unixcmd = ['tksurfer ', subj_FS, ' ', hemi, ' inflated -overlay ',...
            overlay_file, ' -overlay-reg ' reg_file, ' -annot ', annot_file,...
            ' -fthresh ' sprintf('%.4f',my_t)];
        unix(unixcmd)
    else
         % launch tksurfer with the correct arguments
        unixcmd = ['tksurfer ', subj_FS, ' ', hemi, ' inflated -overlay ',...
            overlay_file, ' -overlay-reg ' reg_file, ' -fthresh ' sprintf('%.4f',my_t)];
        unix(unixcmd)
    end
    

end  
